### ISSUE TITLE
Make Player Class

### ISSUE THREAD

**Issue by nstoltzfus3** [nstoltzfus3/TicTacToe#1]
What fields should be included in a Player, what does a Player Class consist of?

**Comment by jlangson** [comment]
Player fields need a name, if it is X or O, and if it is human or AI. 

A Player Class interacts with the board (TicTacToeGame). The Player Class marks an X or an O using a method from TicTacToeGame. Player Class needs to retrieve  the state of the board from TicTacToeGame. For a human this would be a visual display. For an AI this would be an internal representation.

These are my first thoughts.

**Comment by nstoltzfus3** [comment]
I think this is good. Could you make a pull request for a Player class?

**Comment by jlangson** [comment]
I think I need write permissions. I went to push the code and got a permission denied message. 

I'm following the instructions from here which say to push the code then make the pull request. https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

**Comment by nstoltzfus3** [comment]
Issue closed by @jlangson
