### ISSUE TITLE
JUnits:

### ISSUE THREAD

**Issue by nstoltzfus3** [nstoltzfus3/TicTacToe#7]
We need a way to test if our functions are doing the correct things. I suggest setting up a JUnit test structure where each method has tests to ensure they are correctly doing what we expect them to be.

**Comment by jlangson** [comment]
I'd like to take a stab at this. I should have some time this weekend.

**Comment by nstoltzfus3** [comment]
I recommend:
1. Looking up some examples.
2. fragmenting our code into discrete functions that all do 1 or 2 things
3. Making a new JUnit tests only class, it will build portions of the game then test our functions on them.

(4. Why is this useful? Because we want to be able to press a button and make sure anything we build doesn't break what we have already built!)

**Comment by jlangson** [comment]
Started this. I am working on adding test code for TicTacToeGame. My plan is to only write tests for placePiece and findEmpties. I figure the others are simple enough they don't need tests. Agree or disagree?

**Comment by nstoltzfus3** [comment]
This has been addressed. Great work!
